server:
  port: 8000
spring:
  application:
    name: best-zuul
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8001
zuul:
  routes:
    best-auth:
      serviceId: best-auth
      path: /auth/**
      stripPrefix: false
      sensitiveHeaders: '*'
    best-system:
      serviceId: best-system
      path: /system/**
      stripPrefix: true
      sensitiveHeaders: '*'
    best-test:
      serviceId: best-test
      path: /test/**
      stripPrefix: true
      sensitiveHeaders: '*'
  retryable: true
  ribbon:
    eager-load:
      # 开启饥饿加载
      enabled: true
ribbon:
  ReadTimeout: 3000