server:
  port: 8020
spring:
  application:
    name: best-system
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8001
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      # 到认证服务器中校验请求头中的令牌是否是合法令牌
      # 通过当前令牌获取对应用户信息
      user-info-uri: http://localhost:8000/auth/user